pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=eikek-scala-steward[bot]
    actions:
      assign:
        users: [eikek]
      label:
        add: ["dependencies"]
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=eikek-scala-steward[bot]
      - base=main
      - status-success=ci
    actions:
      merge:
        method: merge
