name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  ci-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 100
      - uses: cachix/install-nix-action@v27
      - name: mill ci ${{ github.ref }}
        run: nix develop .#ci --command mill --no-daemon  ci
  ci:
    runs-on: ubuntu-latest
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
