name: Release
on:
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
      - name: Coursier cache
        uses: coursier/cache-action@v6

     - name: Publish library to Maven Central
        if: startsWith(github.ref, 'refs/tags/')
        run: nix develop .#ci --command mill --no-daemon  __.publishSonatypeCentral
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.PGP_SECRET }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
