name: Release
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt ci-release ${{ github.ref }}
        run: nix develop .#ci --command sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
